from enum import Enum


class ErrorCode(Enum):
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    INVALID_OUTPUT_DIR = "INVALID_OUTPUT_DIR"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"

    SCANNER_NOT_FOUND = "SCANNER_NOT_FOUND"
    SCANNER_BUSY = "SCANNER_BUSY"
    SCANNER_NO_PAPER = "SCANNER_NO_PAPER"

    PDF_INVALID = "PDF_INVALID"
    PDF_EMPTY = "PDF_EMPTY"

    CONVERSION_FAILED = "CONVERSION_FAILED"
    UNKNOWN = "UNKNOWN"